version: 2

services:
  web:
    build: .
    volumes:
      - .:/apps/avia_bot
      - ~/.ssh:/root/.ssh
      - ~/.bash_history:/root/.bash_history
    ports:
      - 3000:3000
    command: ./start.sh
  db:
    image: mongodb